version: '3'

services:
  orchestration-service:
    container_name: orchestrator
    depends_on:
      - order-service
    image: alaooluwatobi/soa_orchestration_service:latest
    ports:
      - "3000:8005"
    networks:
      - my_network
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8080/v1
      - INV_SERVICE_URL=http://warehouse-service:8000/v1
      - ORDER_SERVICE_URL=http://order-service:8080
      - NOT_SERVICE_URL=http://notification-service:3000
      - SUB_SERVICE_URL=http://subscription-payment-service:8000
    restart: on-failure
#    restart_policy:
#      condition: on-failure
#      delay: 10s
#      max_attempts: 3
#      window: 60s
  ui-client-service:
    container_name: ui_client
    depends_on:
      - orchestration-service
    image: alaooluwatobi/soa_inventory_client:latest
    ports:
      - "4000:8080"
    networks:
      - my_network
#    environment:
#      - PORT=4000

  auth-service:
    container_name: auth_service
    image: alaooluwatobi/soa_auth_service:latest
    ports:
      - "3001:8080"
    networks:
      - my_network

  warehouse-service:
    container_name: warehouse_service
    image: alaooluwatobi/soa_wh_service:latest
    ports:
      - "3002:8000"
    environment:
      - BUILD_ENVIRONMENT=staging
      - LOCAL_DATABASE_URL=mongodb://localhost:27017
      - ATLAS_DATABASE_URL=mongodb+srv://leonardchinonso:soapassword@cluster0.76mnd.mongodb.net/soa?retryWrites=true&w=majority
      - DATABASE_NAME=soa
    networks:
      - my_network

  order-service:
    container_name: order_service
    image: falug/order:17
    ports:
      - "3003:8080"
    networks:
      - my_network
    environment:
      - WAREHOUSE_SERVICE=warehouse-service:8000
      - MONGO_CONN=mongodb+srv://new-user:d7gxrpwN3Rhzm1vZ@cluster0.nnsd0.mongodb.net/?retryWrites=true&w=majority
      - DB_NAME=IMS
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  notification-service:
    container_name: notification_service
    image: falug/notification:6
    ports:
      - "3004:3000"
    networks:
      - my_network

  subscription-payment-service:
    container_name: subscription_and_payment_service
    image: barotemus/subandpay:latest
    ports:
      - "3005:8000"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
