version: '3'
services:
  auth_service:
    container_name: auth_service
    image: alaooluwatobi/soa_auth_service:latest
    ports:
      - "3001:8080"
    networks:
      - my_network

  warehouse-service:
    container_name: warehouse_service
    image: alaooluwatobi/soa_wh_service:latest
    ports:
      - "3002:8000"
    environment:
      - BUILD_ENVIRONMENT=staging
      - LOCAL_DATABASE_URL=mongodb://localhost:27017
      - ATLAS_DATABASE_URL=mongodb+srv://leonardchinonso:soapassword@cluster0.76mnd.mongodb.net/soa?retryWrites=true&w=majority
      - DATABASE_NAME=soa
    networks:
      - my_network

  order_service:
    container_name: order_service
    image: falug/order:17
    ports:
      - "3003:8080"
    networks:
      - my_network

  notification_service:
    container_name: notification_service
    image: falug/notification:6
    ports:
      - "3004:3000"
    networks:
      - my_network

  subscription_payment_service:
    container_name: subscription_and_payment_service
    image: barotemus/subpay:latest
    ports:
      - "3005:8000"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
